### PR TITLE
Use sdv command for factory mode on and off toggle

### PR DESCRIPTION
**Pull request by wido**
Signed-off-by: Wido den Hollander <wido@widodh.nl>

### CODE REVIEW

**Comment by neon-dev** [comment]
How about
```bash
sdv GUI_factoryMode true
touch /home/tesla/factoryMode
emit-reboot-cid
```
and
```bash
sdv GUI_factoryMode false
rm -f /home/tesla/factoryMode
emit-reboot-cid
```
?
No need to check if the file already exists and the MCU could shut down gracefully instead of when resetting by steering wheel buttons (in case you forget to use `rebcid`).

**Comment by wido** [comment]
Done! How does this look?

**Comment by neon-dev** [comment]
Nice :)

**Comment by neon-dev** [comment]
`rm` without `-f` like you did is fine since we don't show errors anyway (missing file will print a message).

**Comment by Geczy** [comment]
Great work :)__

**Pull request merged**
